name: supase_extension_form
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  country_flags: ^2.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  gap: ^3.0.1
  supabase_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env